version: '2.2'
services:
  db:
    image: mongo:5.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:example
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: "npm start --port 5000"
    ports:
      - "5000:5000"
    environment:
      - JWT_KEY:'secret'
      - MONGODB_STRING:'mongodb://db:27017/test'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: "npm start --port 3000"
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongodb_data:
    driver: local